import{a as R,S as $,i as n}from"./assets/vendor-DnBR8w-b.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&u(c)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function u(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();const B="49640008-31ceefc585112d8f472f2aefe",C="https://pixabay.com/api/";async function g(i,o=1){const{data:a}=await R.get(C,{params:{key:B,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o}});return a}const y=document.querySelector(".gallery"),h=document.querySelector(".loader"),b=document.querySelector(".load-more-btn"),v=document.querySelector(".loading-message");let D=new $(".gallery a",{captionsData:"alt",captionDelay:250});function L(i){const o=i.map(({webformatURL:a,largeImageURL:u,tags:t,likes:r,views:c,comments:q,downloads:M})=>`
        <li class="gallery-item">
            <a href="${u}">
                <div class="image-wrapper">
                    <span class="loader"></span>
                    <img src="${a}" alt="${t}" loading="lazy" onload="this.previousElementSibling.style.display='none'" />
                </div>
            </a>
            <div class="image-info">
                <p class="info-item"><span class="info-value">Likes:</span> ${r}</p>
                <p class="info-item"><span class="info-value">Views:</span> ${c}</p>
                <p class="info-item"><span class="info-value">Comments:</span> ${q}</p>
                <p class="info-item"><span class="info-value">Downloads:</span> ${M}</p>
            </div>
        </li>
    `).join("");y.insertAdjacentHTML("beforeend",o),D.refresh()}function I(){y.innerHTML=""}function E(){h.classList.add("visible")}function S(){h.classList.remove("visible")}function P(){b.classList.remove("is-hidden")}function d(){b.classList.add("is-hidden")}function w(){v.classList.remove("is-hidden")}function x(){v.classList.add("is-hidden")}const m=document.querySelector(".search-form"),O=document.querySelector(".load-more-btn"),s=document.querySelector('input[name="searchQuery"]');let f="",l=1,p=0;d();m.addEventListener("submit",async function(i){if(i.preventDefault(),f=i.target.elements.searchQuery.value.trim(),l=1,!f){n.error({title:"Error",message:"Please enter a search query",position:"topRight"});return}I(),E(),w(),d();try{const o=await g(f,l);if(p=o.totalHits,o.hits.length===0){n.error({title:"Error",message:"No images found. Try again.",position:"topRight"});return}L(o.hits),n.success({title:"Success",message:`Found ${p} images!`,position:"topRight"}),l<Math.ceil(p/15)?P():(d(),n.info({title:"Info",message:"You've reached the end of search results.",position:"topRight"})),m.reset()}catch(o){n.error({title:"Error",message:`Error fetching images: ${o.message}`,position:"topRight"})}finally{S(),x()}});O.addEventListener("click",async function(){E(),w(),l++;try{const i=await g(f,l);if(i.hits.length===0){d(),n.info({title:"Info",message:"You've reached the end of search results.",position:"topRight"});return}L(i.hits);const o=document.querySelector(".gallery-item");if(o){const a=o.getBoundingClientRect().height;window.scrollBy({left:0,top:a*2,behavior:"smooth"})}l>=Math.ceil(p/15)&&(d(),n.info({title:"Info",message:"You've reached the end of search results.",position:"topRight"}))}catch(i){n.error({title:"Error",message:`Error fetching more images: ${i.message}`,position:"topRight"})}finally{S(),x()}});s&&(s.style.width="300px",s.style.padding="10px",s.style.border="2px solid #4E35DE",s.style.borderRadius="8px",s.style.fontSize="16px",s.style.color="#333",s.style.backgroundColor="#f9f9f9",s.style.outline="none",s.style.transition="0.3s",s.addEventListener("focus",()=>{s.style.borderColor="#61dafb",s.style.boxShadow="0 0 10px rgba(97, 218, 251, 0.5)"}),s.addEventListener("blur",()=>{s.style.borderColor="#4E35DE",s.style.boxShadow="none"}));const e=document.querySelector("button[type='submit']");e&&(e.style.padding="12px 24px",e.style.fontSize="16px",e.style.fontWeight="bold",e.style.color="#ffffff",e.style.backgroundColor="#4E35DE",e.style.border="none",e.style.borderRadius="8px",e.style.cursor="pointer",e.style.transition="0.3s",e.addEventListener("mouseover",()=>{e.style.backgroundColor="#61dafb"}),e.addEventListener("mouseout",()=>{e.style.backgroundColor="#4E35DE"}),e.addEventListener("mousedown",()=>{e.style.transform="scale(0.95)"}),e.addEventListener("mouseup",()=>{e.style.transform="scale(1)"}));
//# sourceMappingURL=index.js.map
