import{a as L,S as v,i as u}from"./assets/vendor-DSdoZYMr.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const b="49640008-31ceefc585112d8f472f2aefe",S="https://pixabay.com/api/";async function f(o,t=1){const{data:a}=await L.get(S,{params:{key:b,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}});return a}function p(o){const t=o.map(({webformatURL:n,tags:e,likes:r,views:l,comments:h,downloads:g})=>`
        <li class="gallery-item">
            <a href="${n}">
                <div class="loader"></div>
                <img src="${n}" alt="${e}" />
            </a>
            <div class="image-info">
                <p class="info-item"><span class="info-value">Likes:</span> ${r}</p>
                <p class="info-item"><span class="info-value">Views:</span> ${l}</p>
                <p class="info-item"><span class="info-value">Comments:</span> ${h}</p>
                <p class="info-item"><span class="info-value">Downloads:</span> ${g}</p>
            </div>
        </li>
    `).join("");document.querySelector(".gallery").innerHTML+=t,new v(".gallery a").refresh()}function q(){document.querySelector(".gallery").innerHTML=""}function y(){document.querySelector(".loader").classList.add("visible")}function d(){document.querySelector(".loader").classList.remove("visible")}function M(){document.querySelector(".load-more").classList.add("visible")}function w(){document.querySelector(".load-more").classList.remove("visible")}u.info({title:"Зачекайте",message:"Завантаження нових зображень...",timeout:2e3,position:"topRight"});let c="",i=1,m=0;document.querySelector(".js-image-list");const s=document.querySelector(".js-load-more");document.querySelector(".search-form");document.querySelector(".gallery-item");function H(o){console.log("Touch started",o)}document.addEventListener("touchstart",H,{passive:!0});document.querySelector(".search-form").addEventListener("submit",async o=>{if(o.preventDefault(),c=o.target.elements.searchQuery.value.trim(),i=1,q(),w(),!!c)try{y();const t=await f(c,i);if(d(),m=t.totalHits,t.hits.length===0){u.error({message:"Нічого не знайдено"});return}p(t.hits),i<Math.ceil(m/15)&&M()}catch{d(),u.error({message:"Помилка завантаження"})}});s.addEventListener("click",T);async function T(){i++,s.disabled=!0,s.innerHTML="Loading...",y();try{const o=await f(c,i);d(),p(o.hits),s.disabled=!1,s.innerHTML="Load more",i*15>=m&&(s.classList.replace("load-more","load-more-hidden"),alert("We're sorry, but you've reached the end of search results."));const t=document.querySelector(".gallery-item");if(t){const a=t.getBoundingClientRect().height;window.scrollBy({left:0,top:a*2,behavior:"smooth"})}}catch(o){d(),s.disabled=!1,s.innerHTML="Load more",alert(o.message)}}
//# sourceMappingURL=index.js.map
